#164829153 Chore: setup redux
andela/ah-centauri-frontend pull request #2
Opened 2019-04-29 10:03 UTC by bl4ck4ndbr0wn

#### Description
Setup redux into the current project.

#### How can this be manually tested

Clone the project: `git clone https://github.com/andela/ah-centauri-frontend`

Install dependencies: `yarn install`

`cd` into the project folder

Launch development server: `yarn start`

#### Pivotal Tracker
[Finishes #164829153](https://www.pivotaltracker.com/story/show/164829153)

2019-04-29 17:34 UTC, Mirriam-Maina requested changes
Reduce the number of commits to one. Vincent's commit can be exempted.

2019-04-29 18:30 UTC, bl4ck4ndbr0wn commented
> Reduce the number of commits to one. Vincent's commit can be exempted.

Done.

2019-04-30 07:37 UTC, ValerieRono approved these changes
Looks good Alpha

2019-04-30 08:14 UTC, vino-jasuba approved these changes

2019-04-30 08:17 UTC, merged