#164829158 setup and configure Sass
andela/ah-centauri-frontend pull request #4
Opened 2019-04-29 15:40 UTC by Sm0k3s

#### Description
Setup and configure Sass into the current project.

#### How can this be manually tested

Clone the project: `git clone https://github.com/andela/ah-centauri-frontend`

`cd` into the project folder

Install dependencies: `npm install`

Launch development server: `npm start`

#### Pivotal Tracker
[#164829158](https://www.pivotaltracker.com/story/show/164829158)

2019-04-29 17:05 UTC, vino-jasuba approved these changes

2019-04-30 08:27 UTC, bl4ck4ndbr0wn requested changes
Kindly resolve the merge conflicts.

2019-04-30 08:38 UTC, bl4ck4ndbr0wn approved these changes

2019-04-30 08:41 UTC, ValerieRono approved these changes
Looks good Steve

2019-04-30 08:42 UTC, bl4ck4ndbr0wn approved these changes

2019-04-30 09:32 UTC, merged